name: MUSL

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - ARCH: i486
          - ARCH: i686
          - ARCH: x86_64
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache MUSL Toolchain
        id: cache-musl-toolchain
        uses: actions/cache@v3
        with:
          path: /toolchain
          key: ${{ matrix.ARCH }}-musl-toolchain

      - name: Generate Prime Numbers
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: |
          sudo mkdir -p /toolchain
          sudo chmod 777 /toolchain
          cd /toolchain
          wget https://musl.cc/${{ matrix.ARCH }}-linux-musl-cross.tgz
          tar xvf ${{ matrix.ARCH }}-linux-musl-cross.tgz

      - name: Build
        run: |
          export CC=/toolchain/${{ matrix.ARCH }}-linux-musl-cross/bin/${{ matrix.ARCH }}-linux-musl-cc
          make test
